module.exports.RESET = "\x1b[0m"
module.exports.BRIGHT = "\x1b[1m"
module.exports.DIM = "\x1b[2m"
module.exports.UNDERSCORE = "\x1b[4m"
module.exports.BLINK = "\x1b[5m"
module.exports.REVERSE = "\x1b[7m"
module.exports.HIDDEN = "\x1b[8m"

module.exports.FGBLACK = "\x1b[30m"
module.exports.FGRED = "\x1b[31m"
module.exports.FGYELLOW = "\x1b[33m"
module.exports.FGBLUE = "\x1b[34m"
module.exports.FGMAGENTA = "\x1b[35m"
module.exports.FGCYAN = "\x1b[36m"
module.exports.FGWHITE = "\x1b[37m"

module.exports.BGBLACK = "\x1b[40m"
module.exports.BGRED = "\x1b[41m"
module.exports.BGGREEN = "\x1b[42m"
module.exports.BGYELLOW = "\x1b[43m"
module.exports.BGBLUE = "\x1b[44m"
module.exports.BGMAGENTA = "\x1b[45m"
module.exports.BGCYAN = "\x1b[46m"
module.exports.BGWHITE = "\x1b[47m"